 /* ---------------------------------------------------------------- */
 /* Description                                                      */
 /* ---------------------------------------------------------------- */
 /*                                                                  */
 /* Command ....: RUNALL                                             */
 /* Function ...: all defined pgm's unit test                        */
 /* Startdate ..: 06-01-2012                                         */
 /*                                                                  */
 /* ---------------------------------------------------------------- */
             CMD        PROMPT('REMAIN all defined unit test')

             PARM       KWD(LIBC) TYPE(*CHAR) LEN(10) PROMPT('Library')
